### Add a student
POST http://localhost:5000/student
Content-Type: application/json

{
  "name": "user",
  "email": "user@example.com"
}

### Get all students
GET http://localhost:5000/student

### Get one student
GET http://localhost:5000/student/1


### Update a student
PUT http://localhost:5000/student/1
Content-Type: application/json

{
  "name": "a2",
  "email": "a2@example.com"
}

### Delete a student
DELETE http://localhost:5000/student/1
