### Add a student
POST {{host}}/student
Content-Type: application/json

{
  "name": "user",
  "email": "user@example.com"
}

> {% client.global.set("student_id", response.body.id); %}


### Get all students
GET {{host}}/student

### Get one student
GET {{host}}/student/{{student_id}}


### Update a student
PUT {{host}}/student/{{student_id}}
Content-Type: application/json

{
  "name": "a2",
  "email": "a2@example.com"
}

### Delete a student
DELETE {{host}}/student/{{student_id}}
